apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: xs-nodepool
  namespace: meet-kafka-cluster
  labels:
    strimzi.io/cluster: meet-kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: false
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 2000m
  jvmOptions:
    -Xms: 512m
    -Xmx: 1024m
  template:
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/name
                    operator: In
                    values:
                      - meet-kafka-cluster
              topologyKey: "kubernetes.io/hostname"
