apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: quay.io/strimzi/kafka:0.45.0-kafka-3.9.0
        command:
        - /bin/bash
        - -c
        - bin/kafka-console-consumer.sh --bootstrap-server meet-kafka-cluster-kafka-brokers.meet-kafka-cluster.svc:9092 --topic demo-topic --from-beginning
